"""create meter readings

Revision ID: 000366675e52
Revises: 046e49274dd7
Create Date: 2026-09-22 13:35:58.159179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000366675e52'
down_revision: Union[str, Sequence[str], None] = '046e49274dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('reading_value', sa.Float(), nullable=False),
    sa.Column('previous_reading', sa.Float(), nullable=False),
    sa.Column('consumption_units', sa.Float(), nullable=False),
    sa.Column('reading_type', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_readings_connection_id'), 'meter_readings', ['connection_id'], unique=False)
    op.create_index(op.f('ix_meter_readings_id'), 'meter_readings', ['id'], unique=False)
    op.create_index(op.f('ix_meter_readings_reading_date'), 'meter_readings', ['reading_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meter_readings_reading_date'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_id'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_connection_id'), table_name='meter_readings')
    op.drop_table('meter_readings')
    # ### end Alembic commands ###
