"""create electricity connections

Revision ID: 046e49274dd7
Revises: 9f5738901dfa
Create Date: 2026-09-22 13:31:46.211349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046e49274dd7'
down_revision: Union[str, Sequence[str], None] = '9f5738901dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_number', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('connection_number', sa.String(length=50), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_connection_number'), 'customers', ['connection_number'], unique=True)
    op.create_index(op.f('ix_customers_customer_number'), 'customers', ['customer_number'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=True)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('connection_number', sa.String(length=50), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('tariff_type', sa.String(length=50), nullable=False),
    sa.Column('meter_number', sa.String(length=50), nullable=False),
    sa.Column('meter_type', sa.String(length=50), nullable=False),
    sa.Column('sanctioned_load', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('connection_date', sa.Date(), nullable=False),
    sa.Column('disconnection_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_connection_number'), 'connections', ['connection_number'], unique=True)
    op.create_index(op.f('ix_connections_customer_id'), 'connections', ['customer_id'], unique=False)
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_connections_meter_number'), 'connections', ['meter_number'], unique=True)
    op.create_index(op.f('ix_connections_status'), 'connections', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connections_status'), table_name='connections')
    op.drop_index(op.f('ix_connections_meter_number'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_customer_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_connection_number'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_connection_number'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
