"""create tariffs table

Revision ID: 9b9120752f12
Revises: c6fad65fbc4f
Create Date: 2026-09-23 09:30:23.914879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9120752f12'
down_revision: Union[str, Sequence[str], None] = 'c6fad65fbc4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('slab_name', sa.String(length=100), nullable=False),
    sa.Column('min_units', sa.Float(), nullable=False),
    sa.Column('max_units', sa.Float(), nullable=True),
    sa.Column('rate_per_unit', sa.Float(), nullable=False),
    sa.Column('fixed_charge', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_connection_type'), 'tariffs', ['connection_type'], unique=False)
    op.create_index(op.f('ix_tariffs_effective_from'), 'tariffs', ['effective_from'], unique=False)
    op.create_index(op.f('ix_tariffs_id'), 'tariffs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariffs_id'), table_name='tariffs')
    op.drop_index(op.f('ix_tariffs_effective_from'), table_name='tariffs')
    op.drop_index(op.f('ix_tariffs_connection_type'), table_name='tariffs')
    op.drop_table('tariffs')
    # ### end Alembic commands ###
