"""create service requests

Revision ID: be1c11a8581d
Revises: 98dc56a9e894
Create Date: 2026-09-22 13:53:10.475755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be1c11a8581d'
down_revision: Union[str, Sequence[str], None] = '98dc56a9e894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_connection_id'), 'service_requests', ['connection_id'], unique=False)
    op.create_index(op.f('ix_service_requests_customer_id'), 'service_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_service_requests_id'), 'service_requests', ['id'], unique=False)
    op.create_index(op.f('ix_service_requests_request_number'), 'service_requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_service_requests_status'), 'service_requests', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_bill_id'), 'payments', ['bill_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_payment_reference'), 'payments', ['payment_reference'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_bill_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_service_requests_status'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_request_number'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_customer_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_connection_id'), table_name='service_requests')
    op.drop_table('service_requests')
    # ### end Alembic commands ###
